//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_With_SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pract_18
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string NumberReportBook { get; set; }
        public bool LiveInHostel { get; set; }
        public Nullable<bool> Like1 { get; set; }
        public Nullable<bool> Like2 { get; set; }
        public Nullable<bool> Like3 { get; set; }
        public Nullable<bool> Like4 { get; set; }
        public Nullable<bool> Like5 { get; set; }
    }
}
